// vue-chat/src/components/ChatWindow.vue
<script setup lang="ts">
import MessageList from "./MessageList.vue"
import MessageInput from "./MessageInput.vue"
import ConnectionStatus from "./ConnectionStatus.vue"
import { useChatStore } from "../stores/chatStore"
import { socket } from "../services/socket"

const chat = useChatStore()

function clearHistory(){
  chat.clearMessages()
  socket.emit("clear-history")
}
</script>

<template>
<div>
  <ConnectionStatus />
  <button @click="clearHistory">
    Limpiar historial
  </button>
  <MessageList />
  <MessageInput />
</div>
</template>

// react-chat/src/components/ChatWindow.tsx
import MessageList from "./MessageList"
import MessageInput from "./MessageInput"
import ConnectionStatus from "./ConnectionStatus"
import { useChatStore } from "../store/chatStore"

export default function ChatWindow() {
  const clearMessages = useChatStore((state) => state.clearMessages)

  return (
    <div style={{ marginLeft: "20px" }}>
      <ConnectionStatus />
      <button style={{ marginBottom: "20px" }} onClick={clearMessages}>
        Limpiar historial
      </button>

      <MessageList />
      <MessageInput />
    </div>
  )
}
