// react-chat/src/components/MessageInput.tsx
import { useState } from "react"
import { socket } from "../services/socket"
import { useUserStore } from "../store/userStore"

export default function MessageInput() {
  const username = useUserStore((s) => s.username)
  const setUsername = useUserStore((s) => s.setUsername)
  const [text, setText] = useState("")

  const sendMessage = () => {
    if (!username || !text) return
    socket.emit("message", {
      username,
      text
    })
    setText("")
  }


  return (
    <div>
      <input
        placeholder="User"
        value={username}
        onChange={(e) => setUsername(e.target.value)}
      />

      <input
        placeholder="Mensaje"
        value={text}
        onChange={(e) => setText(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter") sendMessage()
        }}
      />

      <button onClick={sendMessage}>
        Enviar
      </button>

    </div>
  )
}

// vue-chat/src/components/MessageInput.vue
<script setup lang="ts">
import { ref } from "vue"
import { socket } from "../services/socket"
import { useUserStore } from "../stores/userStore"

const user = useUserStore()
const text = ref("")
const usernameInput = ref(user.username)

function updateUsername() {
  user.setUsername(usernameInput.value)
}

function sendMessage() {
  if (!user.username || !text.value) return
  socket.emit("message", {
    username: user.username,
    text: text.value
  })
  text.value = ""
}
</script>

<template>

<div>
  <input
    placeholder="User"
    v-model="usernameInput"
    @change="updateUsername"
  />
  <input
    placeholder="Mensaje"
    v-model="text"
    @keydown.enter="sendMessage"
  />
  <button @click="sendMessage">
    Enviar
  </button>
</div>
</template>
